**Import Libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
from collections import Counter
from sklearn.datasets import load_diabetes, load_iris, fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.metrics import precision_score, recall_score, f1_score, explained_variance_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc
import torch

**Code**

**1. What is PyTorch, and what are its primary uses?**


PyTorch is an open-source machine learning library developed by Facebook's AI Research lab. It's widely used for building and training neural networks due to its flexibility, dynamic computation graph, and strong GPU acceleration.

**Primary Uses of PyTorch:**
- **Deep Learning Research and Development:** PyTorch allows researchers and developers to design complex models with ease, making it popular for cutting-edge research. It supports dynamic computation graphs, which means that the graph is built on the fly as operations are performed. This flexibility is especially useful for models that require complex control flows, such as recurrent neural networks (RNNs) and natural language processing (NLP) tasks.

- **Training and Inference of Neural Networks:** PyTorch provides modules (torch.nn for layers, torch.optim for optimizers, torch.autograd for gradients) that are highly optimized for defining and training deep neural networks. It’s used for computer vision, NLP, reinforcement learning, and more.

- **Data Handling and Augmentation:** PyTorch has utilities like torchvision and torchtext that help load, preprocess, and augment datasets, making it simpler to handle large-scale data for various machine learning tasks.

- **Industry Production and Deployment:** PyTorch offers tools for exporting models to ONNX (Open Neural Network Exchange) and integrations with PyTorch Serve and TorchScript, making it easy to deploy models into production environments.

- **Distributed Training:** PyTorch also includes support for distributed computing, enabling large-scale model training across multiple GPUs or even across nodes in a distributed system.

**2. How do you install PyTorch with GPU support?**

In [2]:
# # Using Pip
# pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

# # Using Conda
# conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

# import torch
# print(torch.cuda.is_available())  # Should return True if GPU is available
# print(torch.cuda.current_device())  # Returns the GPU ID
# print(torch.cuda.get_device_name(0))  # Gets the name of your GPU

**3. What is a tensor, and how is it different from a NumPy array?**

A tensor is a multi-dimensional array used to represent data in PyTorch, similar to a NumPy array in many ways, but with additional features tailored for deep learning and machine learning tasks. Here’s a breakdown of a tensor and how it differs from a NumPy array:

**What is a Tensor?**
- In PyTorch, a tensor is an n-dimensional matrix that generalizes scalars, vectors, and matrices to higher dimensions.
- Tensors can represent any kind of data, including scalars (0D tensors), vectors (1D tensors), matrices (2D tensors), and more (e.g., 3D, 4D, etc.).

**Key Differences Between a Tensor and a NumPy Array:**
- **GPU Support:**
  - PyTorch tensors can be moved to a GPU, allowing for faster computations in parallel, which is essential for training large models.
  - NumPy arrays operate only on the CPU, limiting their use for large-scale deep learning tasks.

- **Automatic Differentiation:**
  - PyTorch tensors support automatic differentiation with torch.autograd, which is essential for deep learning as it allows gradient computation during backpropagation.
  - NumPy arrays do not support automatic differentiation directly, so additional libraries like autograd or JAX are needed to achieve this functionality.

- **Performance and Optimizations:**
  - PyTorch tensors are optimized for deep learning tasks and can leverage libraries like cuDNN and cuBLAS for faster matrix operations on GPUs.
  - While NumPy is also highly optimized for numerical operations on the CPU, it lacks the deep-learning-focused optimizations PyTorch offers.

- **Conversion:**
  - PyTorch tensors and NumPy arrays can be converted to one another easily, allowing flexibility in data handling.
  - torch.from_numpy() converts a NumPy array to a PyTorch tensor, while .numpy() on a tensor (when on CPU) converts it to a NumPy array.
- **Dynamic Computation Graphs:**
  - Tensors in PyTorch support dynamic computation graphs, meaning the graph is created as operations are performed. This allows for more flexibility in model construction, especially with models that have variable-length inputs or changing architectures.
  - NumPy arrays do not offer this capability directly.

**Similarities:**
- Both tensors and NumPy arrays are used for storing multi-dimensional data and support similar indexing, slicing, broadcasting, and element-wise operations.
- They also share many function names, such as .sum(), .mean(), and .reshape(), making it easy for people familiar with NumPy to work with PyTorch.

**4. How do you create a tensor in PyTorch?**

In [3]:
# From a List or Array
import torch
data = [1, 2, 3, 4]
print(data), print(type(data))

tensor_from_list = torch.tensor(data)  # Creates a tensor from a list
print(tensor_from_list), print(type(tensor_from_list))

[1, 2, 3, 4]
<class 'list'>
tensor([1, 2, 3, 4])
<class 'torch.Tensor'>


(None, None)

In [4]:
# Using torch.tensor()
tensor = torch.tensor([5.5, 3.2], dtype=torch.float32)  # Specifies data type
print(tensor)

tensor([5.5000, 3.2000])


In [5]:
# Creating a Tensor with a Specific Shape and Initialization
tensor_zeros = torch.zeros(3, 3)  # Creates a 3x3 tensor of zeros
tensor_ones = torch.ones(2, 2)  # Creates a 2x2 tensor of ones
tensor_random = torch.rand(4, 4)  # Creates a 4x4 tensor with random values
tensor_normal = torch.randn(3, 3)  # 3x3 tensor with normal distribution values
tensor_arange = torch.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
tensor_linspace = torch.linspace(0, 1, steps=5)  # [0., 0.25, 0.5, 0.75, 1.]

In [6]:
# Creating an Identity Matrix
tensor_identity = torch.eye(3)  # 3x3 identity matrix

In [7]:
# Using torch.empty()
tensor_empty = torch.empty(2, 2)  # Creates a 2x2 tensor with uninitialized values
tensor_empty

tensor([[0., 0.],
        [0., 0.]])

In [8]:
# Converting a NumPy Array to a Tensor
import numpy as np
np_array = np.array([1, 2, 3])
tensor_from_numpy = torch.from_numpy(np_array)
tensor_from_numpy

tensor([1, 2, 3])

In [9]:
# Creating a Tensor on a Specific Device (CPU or GPU)
tensor_gpu = torch.tensor([1.0, 2.0, 3.0], device='cpu')  # Requires CUDA-compatible GPU
tensor_gpu

tensor([1., 2., 3.])

**5. How do you convert a tensor to a NumPy array and vice versa?**

In [10]:
# Converting a PyTorch Tensor to a NumPy Array
tensor = torch.tensor([[1, 2], [3, 4]])
numpy_array = tensor.numpy()
print(numpy_array)

[[1 2]
 [3 4]]


In [11]:
# Converting a NumPy Array to a PyTorch Tensor
numpy_array = np.array([[5, 6], [7, 8]])
tensor = torch.from_numpy(numpy_array)
print(tensor)

tensor([[5, 6],
        [7, 8]])


In [12]:
# Example of moving a tensor from GPU to CPU before converting
tensor_gpu = torch.tensor([[1, 2], [3, 4]], device='cuda')
numpy_array = tensor_gpu.cpu().numpy()  # Move to CPU and then convert
numpy_array

array([[1, 2],
       [3, 4]])

In [13]:
tensor = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)
numpy_array = tensor.detach().numpy()  # Detach before converting
numpy_array

array([[1., 2.],
       [3., 4.]], dtype=float32)

**6. How do you check the shape of a tensor in PyTorch?**

In [14]:
# Using the .shape Attribute
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_shape = tensor.shape
print(tensor_shape)

torch.Size([2, 3])


In [15]:
# Using the .size() Method
# Checking the shape of the tensor using size()
tensor_size = tensor.size()
print(tensor_size)

# Getting the size of a specific dimension (e.g., dimension 0)
dim_0_size = tensor.size(0)  # Number of rows
print(dim_0_size)

# Getting the size of a specific dimension (e.g., dimension 1)
dim_1_size = tensor.size(1)  # Number of columns
print(dim_1_size)

torch.Size([2, 3])
2
3


**7. How can you change the shape of a tensor?**

In [16]:
# Using .view() Method
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
reshaped_tensor = tensor.view(3, 2)
print(reshaped_tensor)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [17]:
# Using .reshape() Method
reshaped_tensor = tensor.reshape(2, 3)
print(reshaped_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [18]:
# Using .resize_() Method
tensor = torch.tensor([[1, 2], [3, 4]])
tensor.resize_(4, 2)  # This may lead to unexpected results
print(tensor)

tensor([[                  1,                   2],
        [                  3,                   4],
        [                  0, 7235419174270214779],
        [4122031920162814498, 3774359729567315558]])


**8. What is the purpose of .view() and .reshape() in PyTorch?**

- Use .view() when you are sure that the tensor is contiguous and you want a quick and efficient reshaping.
- Use .reshape() when you are unsure about the contiguity of the tensor, as it can handle both contiguous and non-contiguous cases.

In [19]:
# Purpose of .view()
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
reshaped_tensor = tensor.view(3, 2)
print(reshaped_tensor)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [20]:
# Purpose of .reshape()
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
reshaped_tensor = tensor.reshape(2, 3)
print(reshaped_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


**9. How do you perform element-wise addition on two tensors?**

In [21]:
# Using the + Operator
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
result = tensor1 + tensor2
print(result)  # Output: tensor([5, 7, 9])

tensor([5, 7, 9])


In [22]:
# Using the torch.add() Function
result = torch.add(tensor1, tensor2)
print(result)  # Output: tensor([5, 7, 9])

tensor([5, 7, 9])


In [23]:
# Using In-Place Addition
tensor1 += tensor2
print(tensor1)  # Output: tensor([5, 7, 9])

tensor([5, 7, 9])


In [24]:
# Broadcasting
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([1, 2, 3])  # 1D tensor
result = tensor1 + tensor2
print(result)

tensor([[2, 4, 6],
        [5, 7, 9]])


**10. How do you concatenate two tensors along a specified dimension?**

In [25]:
# Concatenating 1D Tensors
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
result = torch.cat((tensor1, tensor2))
print(result)  # Output: tensor([1, 2, 3, 4, 5, 6])

tensor([1, 2, 3, 4, 5, 6])


In [26]:
# Concatenating 2D Tensors
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
result_dim0 = torch.cat((tensor1, tensor2), dim=0)
print(result_dim0)
result_dim1 = torch.cat((tensor1, tensor2), dim=1)
print(result_dim1)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


**11. How can you slice a tensor in PyTorch?**

In [27]:
x = torch.arange(16).reshape(4, 4)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [28]:
# Select rows or columns
print(x[0, :])    # First row
print(x[:, 1])    # Second column

tensor([0, 1, 2, 3])
tensor([ 1,  5,  9, 13])


In [29]:
# Slicing ranges
print(x[1:3, :])  # Rows 1 and 2
print(x[:, 1:3])  # Columns 1 and 2

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]])


In [30]:
# Advanced slicing
x[::2, ::2]  # Every second row and column

tensor([[ 0,  2],
        [ 8, 10]])

**12. How do you get the number of elements in a tensor?**

In [31]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.numel())

6


**13. How can you check if a tensor is on the GPU?**

In [32]:
x = torch.tensor([1, 2, 3])
print(x.is_cuda)

False


**14. How do you move a tensor to the GPU in PyTorch?**

In [33]:
x = torch.tensor([1, 2, 3])
x = x.to('cuda') if torch.cuda.is_available() else x

In [34]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
x = x.to(device)

**15. How do you move a tensor back to the CPU?**

In [35]:
x = x.to('cpu')

**16. What’s the difference between .detach() and .requires_grad=False?**

In [36]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x.detach()
y

tensor([1., 2., 3.])

In [37]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
x.requires_grad = False
x

tensor([1., 2., 3.])

**17. How do you transpose a tensor?**

In [38]:
# Using .transpose(dim0, dim1)
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x_transposed = x.transpose(0, 1)
print(x_transposed)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [39]:
# Using .t() (for 2D matrices only)
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x_t = x.t()
print(x_t)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [40]:
# Using .permute(*dims) for Arbitrary Dimensionality
x = torch.randn(2, 3, 4)  # Example 3D tensor
x_permuted = x.permute(2, 0, 1)  # Change order of dimensions
print(x_permuted.shape)

torch.Size([4, 2, 3])


**18. What’s the difference between .t() and .transpose()?**

- .t() for quick 2D transpositions, and .transpose() for more flexible, multi-dimensional transpositions.

**19. How can you initialize a tensor with random values?**

In [41]:
# Uniformly Distributed Random Values: torch.rand()
x = torch.rand(3, 3)  # 3x3 tensor with values in [0, 1)
print(x)

tensor([[0.8302, 0.2694, 0.3707],
        [0.9966, 0.0659, 0.8029],
        [0.5867, 0.1673, 0.1953]])


In [42]:
# Normally Distributed Random Values: torch.randn()
x = torch.randn(3, 3)  # 3x3 tensor with values from N(0, 1)
print(x)

tensor([[-0.8434, -0.8812, -1.1155],
        [ 0.0643,  2.0888, -1.1783],
        [ 0.0121, -1.0492, -0.0210]])


In [43]:
# Random Integers: torch.randint()
x = torch.randint(0, 10, (3, 3))  # 3x3 tensor with integer values in [0, 10)
print(x)

tensor([[9, 3, 9],
        [6, 4, 3],
        [5, 5, 4]])


In [44]:
# Random Values in a Specified Range: torch.empty() with .uniform_() or .normal_()
# Uniformly distributed values in [a, b]
x = torch.empty(3, 3).uniform_(-1, 1)
print(x)

# Normally distributed values with mean and std deviation
x = torch.empty(3, 3).normal_(mean=0, std=1)
print(x)

tensor([[ 0.3882, -0.2747, -0.9303],
        [ 0.6378,  0.1922,  0.5275],
        [-0.2408,  0.7307, -0.0566]])
tensor([[ 0.0026,  0.4301, -0.5090],
        [ 2.1904, -1.7123, -0.5905],
        [ 0.8708, -1.1731,  0.0767]])


**20. How do you create a tensor filled with ones, zeros, or a specific value?**

In [45]:
# Tensor Filled with Zeros: torch.zeros()
x = torch.zeros(3, 3)  # Creates a 3x3 tensor of zeros
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [46]:
# Tensor Filled with Ones: torch.ones()
x = torch.ones(3, 3)  # Creates a 3x3 tensor of ones
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [47]:
# Tensor Filled with a Specific Value: torch.full()
x = torch.full((3, 3), 7)  # Creates a 3x3 tensor filled with the value 7
print(x)

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])


**21. What is the difference between a scalar, vector, matrix, and tensor in PyTorch?**

In [48]:
# Scalar - 0D () Single value
scalar = torch.tensor(5)  # Scalar tensor with a single value
print(scalar)             # Output: tensor(5)
print(scalar.shape)       # Output: torch.Size([])

tensor(5)
torch.Size([])


In [49]:
# Vector - 1D (n,) One-dimensional array
vector = torch.tensor([1, 2, 3])  # Vector tensor with 3 elements
print(vector)                     # Output: tensor([1, 2, 3])
print(vector.shape)               # Output: torch.Size([3])

tensor([1, 2, 3])
torch.Size([3])


In [50]:
# Matrix - 2D (n, m) Two-dimensional array
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])  # 2x3 matrix
print(matrix)                                  # Output: tensor([[1, 2, 3], [4, 5, 6]])
print(matrix.shape)                            # Output: torch.Size([2, 3])

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [51]:
# Tensor (Higher-dimensional) - 3D or more (n, m, p, ...) Multi-dimensional array
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3D tensor
print(tensor_3d)              # Output: tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor_3d.shape)        # Output: torch.Size([2, 2, 2])

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


**22. How do you create a tensor with random values between 0 and 1?**

In [52]:
random_tensor = torch.rand(3, 3)
print(random_tensor)

tensor([[0.2326, 0.5601, 0.2636],
        [0.6543, 0.7685, 0.1023],
        [0.0541, 0.1579, 0.3964]])


**23. How do you create an identity matrix tensor in PyTorch?**

In [53]:
identity_matrix = torch.eye(3)
print(identity_matrix)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [54]:
identity_like_matrix = torch.eye(3, 4)
print(identity_like_matrix)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


**24. How do you generate a tensor with values from a normal distribution in PyTorch?**

In [55]:
# Using torch.randn()
standard_normal_tensor = torch.randn(3, 3)
print(standard_normal_tensor)

tensor([[-0.3133, -0.1716,  1.6374],
        [ 1.0650,  0.8057,  0.5872],
        [-0.0242, -1.4778,  1.8295]])


In [56]:
# Using torch.normal()
mean = 5.0
std_dev = 2.0
custom_normal_tensor = torch.normal(mean, std_dev, size=(3, 3))
print(custom_normal_tensor)

tensor([[7.3190, 4.0043, 7.5515],
        [3.7856, 3.3593, 3.7145],
        [2.6327, 3.9001, 3.6215]])


**25. What’s the difference between torch.arange() and torch.linspace()?**

In [57]:
# torch.arange()
tensor_arange = torch.arange(0, 10, 1)
print(tensor_arange)  # Output: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [58]:
# torch.linspace()
tensor_linspace = torch.linspace(0, 10, steps=5)
print(tensor_linspace)  # Output: tensor([ 0.,  2.5,  5.,  7.5, 10.])

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


**26. How do you set the random seed in PyTorch for reproducibility?**

In [59]:
torch.manual_seed(42)
random_tensor = torch.rand(3, 3)
print(random_tensor)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


**27. How can you convert a Python list or tuple directly into a PyTorch tensor?**

In [60]:
my_tuple = (6, 7, 8, 9, 10)
tensor_from_tuple = torch.tensor(my_tuple)
print(tensor_from_tuple)

tensor([ 6,  7,  8,  9, 10])


In [61]:
nested_list = [[1, 2, 3], [4, 5, 6]]
tensor_from_nested = torch.tensor(nested_list)
print(tensor_from_nested)

tensor([[1, 2, 3],
        [4, 5, 6]])


**28. How do you create a tensor that starts at a given value and ends at a specified value?**

In [62]:
# Using torch.arange()
tensor_arange = torch.arange(5, 10, 1)
print(tensor_arange)

tensor([5, 6, 7, 8, 9])


In [63]:
# Using torch.linspace()
tensor_linspace = torch.linspace(5, 10, steps=5)
print(tensor_linspace)

tensor([ 5.0000,  6.2500,  7.5000,  8.7500, 10.0000])


**29. How can you add a new dimension to a tensor?**

In [64]:
# Using torch.unsqueeze()
# Create a 1D tensor
tensor_1d = torch.tensor([1, 2, 3, 4, 5])
print("Original tensor:", tensor_1d)
print("Shape:", tensor_1d.shape)

# Add a new dimension at axis 0
tensor_2d = torch.unsqueeze(tensor_1d, dim=0)
print("After unsqueeze (axis 0):", tensor_2d)
print("Shape:", tensor_2d.shape)

# Add a new dimension at axis 1
tensor_2d_2 = torch.unsqueeze(tensor_1d, dim=1)
print("After unsqueeze (axis 1):", tensor_2d_2)
print("Shape:", tensor_2d_2.shape)

Original tensor: tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])
After unsqueeze (axis 0): tensor([[1, 2, 3, 4, 5]])
Shape: torch.Size([1, 5])
After unsqueeze (axis 1): tensor([[1],
        [2],
        [3],
        [4],
        [5]])
Shape: torch.Size([5, 1])


In [65]:
# Using None Indexing
# Add a new dimension at axis 0 using None indexing
tensor_2d_none = tensor_1d[None, :]
print("After None indexing (axis 0):", tensor_2d_none)
print("Shape:", tensor_2d_none.shape)

# Add a new dimension at axis 1 using None indexing
tensor_2d_none_2 = tensor_1d[:, None]
print("After None indexing (axis 1):", tensor_2d_none_2)
print("Shape:", tensor_2d_none_2.shape)

After None indexing (axis 0): tensor([[1, 2, 3, 4, 5]])
Shape: torch.Size([1, 5])
After None indexing (axis 1): tensor([[1],
        [2],
        [3],
        [4],
        [5]])
Shape: torch.Size([5, 1])


In [66]:
# Using torch.reshape()
# Reshape to add a new dimension
tensor_reshaped = tensor_1d.reshape(1, -1)  # Adds a new dimension
print("After reshape (1, -1):", tensor_reshaped)
print("Shape:", tensor_reshaped.shape)

After reshape (1, -1): tensor([[1, 2, 3, 4, 5]])
Shape: torch.Size([1, 5])


**30. What is broadcasting in PyTorch, and how does it work?**

In [67]:
# Simple Broadcasting
A = torch.tensor([[1], [2], [3]])
B = torch.tensor([[10, 20, 30, 40]])
result = A + B
print(result)

tensor([[11, 21, 31, 41],
        [12, 22, 32, 42],
        [13, 23, 33, 43]])


In [68]:
# Broadcasting with Different Dimensions
C = torch.tensor([1, 2])
result_2 = A + C  # C is treated as (1, 2) and then broadcast to (3, 2)
print(result_2)

tensor([[2, 3],
        [3, 4],
        [4, 5]])


**31. How do you perform matrix multiplication on two tensors?**

- Use torch.matmul(A, B) or A @ B for matrix multiplication of 2D tensors (or higher-dimensional tensors).
- Use torch.mm(A, B) specifically for 2D tensor multiplication.

In [69]:
# Using torch.matmul()
A = torch.tensor([[1, 2],
                  [3, 4]])
B = torch.tensor([[5, 6],
                  [7, 8]])
result = torch.matmul(A, B)
print("Result of A @ B using torch.matmul():\n", result)

Result of A @ B using torch.matmul():
 tensor([[19, 22],
        [43, 50]])


In [70]:
# Using the @ Operator
result_operator = A @ B
print("Result of A @ B using @ operator:\n", result_operator)

Result of A @ B using @ operator:
 tensor([[19, 22],
        [43, 50]])


In [71]:
# Using torch.mm()
result_mm = torch.mm(A, B)
print("Result of A @ B using torch.mm():\n", result_mm)

Result of A @ B using torch.mm():
 tensor([[19, 22],
        [43, 50]])


**32. How do you calculate the dot product of two tensors?**

- Use torch.dot(a, b) for the dot product of two 1D tensors (vectors).
- Use torch.matmul(a, b) or the @ operator for the dot product, which works for both 1D and 2D tensors. When using 1D tensors, they yield the same result as torch.dot().

In [72]:
# Using torch.dot()
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
dot_product = torch.dot(a, b)
print("Dot product using torch.dot():", dot_product)

Dot product using torch.dot(): tensor(32)


In [73]:
# Using torch.matmul()
dot_product_matmul = torch.matmul(a, b)
print("Dot product using torch.matmul():", dot_product_matmul)

Dot product using torch.matmul(): tensor(32)


In [74]:
# Using the @ Operator
dot_product_operator = a @ b
print("Dot product using @ operator:", dot_product_operator)

Dot product using @ operator: tensor(32)


**33. How can you find the mean, median, and standard deviation of a tensor?**

In [75]:
# Create a 2D tensor
tensor_2d = torch.tensor([[1.0, 2.0, 3.0],
                           [4.0, 5.0, 6.0]])

# Calculate the mean along dimension 0 (columns)
mean_dim0 = torch.mean(tensor_2d, dim=0)
print("Mean along dimension 0:", mean_dim0)

# Calculate the median along dimension 1 (rows)
median_dim1 = torch.median(tensor_2d, dim=1).values
print("Median along dimension 1:", median_dim1)

# Calculate the standard deviation along dimension 0
std_dim0 = torch.std(tensor_2d, dim=0)
print("Standard Deviation along dimension 0:", std_dim0)

Mean along dimension 0: tensor([2.5000, 3.5000, 4.5000])
Median along dimension 1: tensor([2., 5.])
Standard Deviation along dimension 0: tensor([2.1213, 2.1213, 2.1213])


**34. How do you calculate the maximum and minimum values in a tensor?**

In [76]:
# Finding Overall Maximum and Minimum Values
tensor = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])

# Calculate the maximum value
max_value = torch.max(tensor)
print("Maximum value:", max_value)

# Calculate the minimum value
min_value = torch.min(tensor)
print("Minimum value:", min_value)

Maximum value: tensor(5.)
Minimum value: tensor(1.)


In [77]:
# Finding Maximum and Minimum Along a Specific Dimension
# Create a 2D tensor
tensor_2d = torch.tensor([[1.0, 2.0, 3.0],
                           [4.0, 5.0, 6.0]])

# Calculate the maximum values along dimension 0 (columns)
max_dim0 = torch.max(tensor_2d, dim=0)
print("Maximum values along dimension 0:", max_dim0.values)

# Calculate the minimum values along dimension 1 (rows)
min_dim1 = torch.min(tensor_2d, dim=1)
print("Minimum values along dimension 1:", min_dim1.values)

Maximum values along dimension 0: tensor([4., 5., 6.])
Minimum values along dimension 1: tensor([1., 4.])


**35. How can you calculate the cumulative sum along a specified dimension of a tensor?**

In [78]:
# Cumulative Sum of a 1D Tensor
tensor_1d = torch.tensor([1.0, 2.0, 3.0, 4.0])
cumsum_1d = torch.cumsum(tensor_1d, dim=0)
print("Cumulative sum of 1D tensor:", cumsum_1d)

Cumulative sum of 1D tensor: tensor([ 1.,  3.,  6., 10.])


In [79]:
# Cumulative Sum of a 2D Tensor
tensor_2d = torch.tensor([[1.0, 2.0, 3.0],
                           [4.0, 5.0, 6.0]])

# Calculate the cumulative sum along dimension 0 (columns)
cumsum_dim0 = torch.cumsum(tensor_2d, dim=0)
print("Cumulative sum along dimension 0:\n", cumsum_dim0)

# Calculate the cumulative sum along dimension 1 (rows)
cumsum_dim1 = torch.cumsum(tensor_2d, dim=1)
print("Cumulative sum along dimension 1:\n", cumsum_dim1)

Cumulative sum along dimension 0:
 tensor([[1., 2., 3.],
        [5., 7., 9.]])
Cumulative sum along dimension 1:
 tensor([[ 1.,  3.,  6.],
        [ 4.,  9., 15.]])


**36. How do you clone a tensor in PyTorch?**

In [80]:
# Cloning a 1D Tensor
original_tensor = torch.tensor([1.0, 2.0, 3.0])
cloned_tensor = original_tensor.clone()
cloned_tensor[0] = 10.0
print("Original tensor:", original_tensor)
print("Cloned tensor:", cloned_tensor)

Original tensor: tensor([1., 2., 3.])
Cloned tensor: tensor([10.,  2.,  3.])


In [81]:
# Cloning a 2D Tensor
original_tensor_2d = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
cloned_tensor_2d = original_tensor_2d.clone()
cloned_tensor_2d[0, 0] = 10.0
print("Original 2D tensor:\n", original_tensor_2d)
print("Cloned 2D tensor:\n", cloned_tensor_2d)

Original 2D tensor:
 tensor([[1., 2.],
        [3., 4.]])
Cloned 2D tensor:
 tensor([[10.,  2.],
        [ 3.,  4.]])


**37. How do you perform element-wise multiplication of two tensors?**

- Use the * operator or torch.mul() function to perform element-wise multiplication of two tensors.

In [82]:
# Using the * Operator
tensor_a = torch.tensor([1.0, 2.0, 3.0])
tensor_b = torch.tensor([4.0, 5.0, 6.0])
result = tensor_a * tensor_b
print("Element-wise multiplication using * operator:", result)

Element-wise multiplication using * operator: tensor([ 4., 10., 18.])


In [83]:
# Using the torch.mul() Function
result_mul = torch.mul(tensor_a, tensor_b)
print("Element-wise multiplication using torch.mul():", result_mul)

Element-wise multiplication using torch.mul(): tensor([ 4., 10., 18.])


In [84]:
# Create two 2D tensors
tensor_2d_a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
tensor_2d_b = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

# Element-wise multiplication
result_2d = tensor_2d_a * tensor_2d_b
print("Element-wise multiplication of 2D tensors:\n", result_2d)

Element-wise multiplication of 2D tensors:
 tensor([[ 5., 12.],
        [21., 32.]])


**38. How can you compare two tensors element-wise in PyTorch?**

In [85]:
# Create two tensors
tensor_a = torch.tensor([1.0, 2.0, 3.0])
tensor_b = torch.tensor([2.0, 2.0, 1.0])

# Element-wise equality
equal = tensor_a == tensor_b
print("Equal (tensor_a == tensor_b):", equal)

# Element-wise inequality
not_equal = tensor_a != tensor_b
print("Not equal (tensor_a != tensor_b):", not_equal)

# Less than
less_than = tensor_a < tensor_b
print("Less than (tensor_a < tensor_b):", less_than)

# Less than or equal to
less_than_equal = tensor_a <= tensor_b
print("Less than or equal to (tensor_a <= tensor_b):", less_than_equal)

# Greater than
greater_than = tensor_a > tensor_b
print("Greater than (tensor_a > tensor_b):", greater_than)

# Greater than or equal to
greater_than_equal = tensor_a >= tensor_b
print("Greater than or equal to (tensor_a >= tensor_b):", greater_than_equal)


Equal (tensor_a == tensor_b): tensor([False,  True, False])
Not equal (tensor_a != tensor_b): tensor([ True, False,  True])
Less than (tensor_a < tensor_b): tensor([ True, False, False])
Less than or equal to (tensor_a <= tensor_b): tensor([ True,  True, False])
Greater than (tensor_a > tensor_b): tensor([False, False,  True])
Greater than or equal to (tensor_a >= tensor_b): tensor([False,  True,  True])


**39. What is the difference between .item() and .tolist() when working with tensors?**

- Use .item() when you need to retrieve a single value from a scalar tensor
- Use .tolist() when you want to convert a tensor of any shape into a list.

In [86]:
# .item()
scalar_tensor = torch.tensor(5.0)
value = scalar_tensor.item()
print("Value from scalar tensor:", value)  # Output: 5.0

Value from scalar tensor: 5.0


In [87]:
# .tolist()
tensor_1d = torch.tensor([1.0, 2.0, 3.0])
list_1d = tensor_1d.tolist()
print("List from 1D tensor:", list_1d)  # Output: [1.0, 2.0, 3.0]
tensor_2d = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
list_2d = tensor_2d.tolist()
print("List from 2D tensor:", list_2d)  # Output: [[1.0, 2.0], [3.0, 4.0]]

List from 1D tensor: [1.0, 2.0, 3.0]
List from 2D tensor: [[1.0, 2.0], [3.0, 4.0]]


**40. How do you split a tensor into multiple sub-tensors?**

- torch.split(): Use this when you want to specify the exact sizes of each sub-tensor or when the sizes are not uniform.
- torch.chunk(): Use this when you want to divide a tensor into a specific number of equal parts.

In [88]:
# Using torch.split()
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_tensors = torch.split(tensor, [1, 2], dim=0)
for i, sub_tensor in enumerate(sub_tensors):
    print(f"Sub-tensor {i}:\n{sub_tensor}")

Sub-tensor 0:
tensor([[1, 2, 3]])
Sub-tensor 1:
tensor([[4, 5, 6],
        [7, 8, 9]])


In [89]:
# Using torch.chunk()
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
chunks = torch.chunk(tensor, 3, dim=0)
for i, chunk in enumerate(chunks):
    print(f"Chunk {i}:\n{chunk}")

Chunk 0:
tensor([[1, 2, 3],
        [4, 5, 6]])
Chunk 1:
tensor([[ 7,  8,  9],
        [10, 11, 12]])


**41. How can you stack multiple tensors along a new dimension?**

In [90]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
tensor3 = torch.tensor([[9, 10], [11, 12]])
stacked_tensor = torch.stack((tensor1, tensor2, tensor3), dim=0)
print("Stacked Tensor:\n", stacked_tensor)
print("Shape of Stacked Tensor:", stacked_tensor.shape)

Stacked Tensor:
 tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
Shape of Stacked Tensor: torch.Size([3, 2, 2])


In [91]:
# Stack along dim=1
stacked_tensor_dim1 = torch.stack((tensor1, tensor2, tensor3), dim=1)
print("Stacked Tensor along dim=1:\n", stacked_tensor_dim1)
print("Shape:", stacked_tensor_dim1.shape)

# Stack along dim=2
stacked_tensor_dim2 = torch.stack((tensor1, tensor2, tensor3), dim=2)
print("Stacked Tensor along dim=2:\n", stacked_tensor_dim2)
print("Shape:", stacked_tensor_dim2.shape)

Stacked Tensor along dim=1:
 tensor([[[ 1,  2],
         [ 5,  6],
         [ 9, 10]],

        [[ 3,  4],
         [ 7,  8],
         [11, 12]]])
Shape: torch.Size([2, 3, 2])
Stacked Tensor along dim=2:
 tensor([[[ 1,  5,  9],
         [ 2,  6, 10]],

        [[ 3,  7, 11],
         [ 4,  8, 12]]])
Shape: torch.Size([2, 2, 3])


**42. How do you perform in-place operations on a tensor, and what are the implications?**

In [92]:
# In-Place Addition
tensor = torch.tensor([1, 2, 3])
tensor.add_(5)  # Adds 5 to each element in-place
print(tensor)  # Output: tensor([6, 7, 8])

tensor([6, 7, 8])


In [93]:
# In-Place Multiplication
tensor.mul_(2)  # Multiplies each element by 2 in-place
print(tensor)  # Output: tensor([12, 14, 16])

tensor([12, 14, 16])


In [94]:
# In-Place Zeroing
tensor.zero_()  # Sets all elements to zero in-place
print(tensor)  # Output: tensor([0, 0, 0])

tensor([0, 0, 0])


**43. How do you fill a tensor with a specific value in PyTorch?**

- Use tensor.fill_(value) to fill an existing tensor in-place with a specific value.
- Use torch.full(size, value) to create a new tensor of the specified size filled with a specific value.

In [95]:
# Using torch.fill_()
tensor = torch.zeros(3, 4)  # A 3x4 tensor
tensor.fill_(7)
print(tensor)

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])


In [96]:
# Using torch.full()
tensor = torch.full((2, 3), 5)  # A 2x3 tensor filled with 5
print(tensor)

tensor([[5, 5, 5],
        [5, 5, 5]])


**44. What’s the difference between .sum() and .prod() on a tensor?**

In [97]:
# .sum()
tensor = torch.tensor([[1, 2], [3, 4]])

# Sum of all elements
total_sum = tensor.sum()
print("Total Sum:", total_sum)  # Output: Total Sum: tensor(10)

# Sum along dimension 0 (columns)
sum_dim0 = tensor.sum(dim=0)
print("Sum along dimension 0:", sum_dim0)  # Output: Sum along dimension 0: tensor([4, 6])

# Sum along dimension 1 (rows)
sum_dim1 = tensor.sum(dim=1)
print("Sum along dimension 1:", sum_dim1)  # Output: Sum along dimension 1: tensor([3, 7])

Total Sum: tensor(10)
Sum along dimension 0: tensor([4, 6])
Sum along dimension 1: tensor([3, 7])


In [98]:
# .prod()
tensor = torch.tensor([[1, 2], [3, 4]])

# Product of all elements
total_prod = tensor.prod()
print("Total Product:", total_prod)  # Output: Total Product: tensor(24)

# Product along dimension 0 (columns)
prod_dim0 = tensor.prod(dim=0)
print("Product along dimension 0:", prod_dim0)  # Output: Product along dimension 0: tensor([3, 8])

# Product along dimension 1 (rows)
prod_dim1 = tensor.prod(dim=1)
print("Product along dimension 1:", prod_dim1)  # Output: Product along dimension 1: tensor([ 2, 12])

Total Product: tensor(24)
Product along dimension 0: tensor([3, 8])
Product along dimension 1: tensor([ 2, 12])


**45. How do you concatenate two tensors along a specific axis?**

In [99]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6]])

# Concatenate along dimension 0 (rows)
result_dim0 = torch.cat((tensor1, tensor2), dim=0)
print("Concatenated along dimension 0:\n", result_dim0)

# Create two example tensors with the same number of rows
tensor3 = torch.tensor([[7, 8]])
tensor4 = torch.tensor([[9, 10]])

# Concatenate along dimension 1 (columns)
result_dim1 = torch.cat((tensor3, tensor4), dim=1)
print("Concatenated along dimension 1:\n", result_dim1)

Concatenated along dimension 0:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
Concatenated along dimension 1:
 tensor([[ 7,  8,  9, 10]])


**46. How can you reverse a tensor along a specific dimension?**

In [100]:
# Create an example tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reverse along dimension 0 (rows)
reversed_dim0 = torch.flip(tensor, dims=[0])
print("Reversed along dimension 0:\n", reversed_dim0)

# Reverse along dimension 1 (columns)
reversed_dim1 = torch.flip(tensor, dims=[1])
print("Reversed along dimension 1:\n", reversed_dim1)

# Reverse along both dimensions
reversed_both = torch.flip(tensor, dims=[0, 1])
print("Reversed along both dimensions:\n", reversed_both)

Reversed along dimension 0:
 tensor([[4, 5, 6],
        [1, 2, 3]])
Reversed along dimension 1:
 tensor([[3, 2, 1],
        [6, 5, 4]])
Reversed along both dimensions:
 tensor([[6, 5, 4],
        [3, 2, 1]])


**47. How do you round elements in a tensor to the nearest integer?**

In [101]:
tensor = torch.tensor([[1.2, 2.5, 3.7], [4.4, 5.8, 6.0]])
rounded_tensor = torch.round(tensor)
print("Original Tensor:\n", tensor)
print("Rounded Tensor:\n", rounded_tensor)

Original Tensor:
 tensor([[1.2000, 2.5000, 3.7000],
        [4.4000, 5.8000, 6.0000]])
Rounded Tensor:
 tensor([[1., 2., 4.],
        [4., 6., 6.]])


**48. How can you create a tensor that’s uniformly distributed within a range?**

In [102]:
# Using torch.rand() and Scaling
a = 5  # Lower bound
b = 10  # Upper bound
# Create a tensor with shape (3, 4) uniformly distributed within the range [5, 10]
uniform_tensor = a + (b - a) * torch.rand(3, 4)
print("Uniformly distributed tensor:\n", uniform_tensor)

Uniformly distributed tensor:
 tensor([[5.6659, 9.6730, 7.9679, 9.3470],
        [7.8386, 8.7055, 7.1470, 9.4272],
        [7.8695, 6.3329, 8.1372, 6.3482]])


In [103]:
# Using torch.empty() and uniform_()
a = 5  # Lower bound
b = 10  # Upper bound
# Create a tensor with shape (3, 4) uniformly distributed within the range [5, 10]
uniform_tensor = torch.empty(3, 4).uniform_(a, b)
print("Uniformly distributed tensor:\n", uniform_tensor)

Uniformly distributed tensor:
 tensor([[7.2068, 6.4846, 9.1584, 5.5266],
        [6.3475, 6.7941, 5.9968, 7.7360],
        [5.0308, 9.7578, 5.3763, 9.4301]])


**49. How do you reshape a tensor to make it compatible for matrix multiplication?**

In [104]:
# Step 1: Create a tensor A with shape (4, 2)
A = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6],
                  [7, 8]])

# Print original shape of A
print("Original shape of A:", A.shape)  # Output: torch.Size([4, 2])

# Step 2: Reshape A to (2, 4)
A_reshaped = A.reshape(2, 4)

# Print the reshaped tensor and its shape
print("Reshaped A:\n", A_reshaped)
print("Shape of reshaped A:", A_reshaped.shape)  # Output: torch.Size([2, 4])

# Step 3: Create a tensor B with shape (4, 3)
B = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])

# Print shape of B
print("Shape of B:", B.shape)  # Output: torch.Size([4, 3])

# Step 4: Perform matrix multiplication
result = torch.mm(A_reshaped, B)

# Print the result
print("Matrix multiplication result:\n", result)
print("Shape of the result:", result.shape)  # Output: torch.Size([2, 3])

Original shape of A: torch.Size([4, 2])
Reshaped A:
 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
Shape of reshaped A: torch.Size([2, 4])
Shape of B: torch.Size([4, 3])
Matrix multiplication result:
 tensor([[ 70,  80,  90],
        [158, 184, 210]])
Shape of the result: torch.Size([2, 3])


**50. How do you find the indices of the maximum values in a tensor along a specific axis?**

- Use torch.max(tensor, dim=0) to get the maximum values and their indices along the columns.
- Use torch.max(tensor, dim=1) to get the maximum values and their indices along the rows.

In [105]:
# Create a 2D tensor
tensor = torch.tensor([[1, 3, 2],
                       [4, 1, 5],
                       [7, 6, 0]])

# Print the original tensor
print("Original Tensor:\n", tensor)

# Find the indices of the maximum values along dimension 0 (columns)
max_values_col, max_indices_col = torch.max(tensor, dim=0)

# Print results for columns
print("Max values along columns:", max_values_col)       # Output: max values for each column
print("Indices of max values along columns:", max_indices_col)  # Indices of max values for each column

# Find the indices of the maximum values along dimension 1 (rows)
max_values_row, max_indices_row = torch.max(tensor, dim=1)

# Print results for rows
print("Max values along rows:", max_values_row)         # Output: max values for each row
print("Indices of max values along rows:", max_indices_row)   # Indices of max values for each row

Original Tensor:
 tensor([[1, 3, 2],
        [4, 1, 5],
        [7, 6, 0]])
Max values along columns: tensor([7, 6, 5])
Indices of max values along columns: tensor([2, 2, 1])
Max values along rows: tensor([3, 5, 7])
Indices of max values along rows: tensor([1, 2, 0])


**51. What is the tile function in PyTorch, and how is it used?**

In [106]:
# Create a 1D tensor
tensor_1d = torch.tensor([1, 2, 3])
print("Original 1D tensor:", tensor_1d)

# Tile the 1D tensor: repeat it 3 times
tiled_1d = torch.tile(tensor_1d, (3,))
print("Tiled 1D tensor:", tiled_1d)

# Create a 2D tensor
tensor_2d = torch.tensor([[1, 2],
                          [3, 4]])
print("Original 2D tensor:\n", tensor_2d)

# Tile the 2D tensor: repeat it 2 times along the first dimension and 3 times along the second dimension
tiled_2d = torch.tile(tensor_2d, (2, 3))
print("Tiled 2D tensor:\n", tiled_2d)

Original 1D tensor: tensor([1, 2, 3])
Tiled 1D tensor: tensor([1, 2, 3, 1, 2, 3, 1, 2, 3])
Original 2D tensor:
 tensor([[1, 2],
        [3, 4]])
Tiled 2D tensor:
 tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4],
        [1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]])
